In [2]:
import os 
import numpy as np
from matplotlib import pyplot as plt
import cv2

In [3]:
work_dir = 'c:/Users/Jalil/Desktop/Ecole/M2TSI/tp2/'
dataset_toystory_path = os.path.join(work_dir, 'datasets/toy_story_1_01')
dataset_ernest_path = os.path.join(work_dir, 'datasets/Movies/ernest_celestine_01')

In [4]:
image_mat = np.empty((1000, 540, 920, 3))

In [24]:
a = np.array([[1,2],[5,6]])
b = np.array([[3,4], [7,8]])
print(np.concatenate((a,b)))

[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [17]:
for i, file in enumerate(os.listdir(os.path.join(work_dir, dataset_toystory_path))):
    image_mat[i] = cv2.imread(os.path.join(work_dir, dataset_toystory_path, file))
    
    

In [18]:
print(image_mat.shape)

(1000, 540, 920, 3)


In [20]:
print(image_mat[10])

[[[ 63. 133. 217.]
  [ 63. 133. 217.]
  [ 65. 133. 217.]
  ...
  [101. 101. 107.]
  [101. 101. 107.]
  [101. 101. 107.]]

 [[ 63. 133. 217.]
  [ 63. 133. 217.]
  [ 65. 133. 217.]
  ...
  [101. 101. 107.]
  [101. 101. 107.]
  [101. 101. 107.]]

 [[ 63. 133. 217.]
  [ 63. 133. 217.]
  [ 65. 133. 217.]
  ...
  [101. 101. 107.]
  [101. 101. 107.]
  [101. 101. 107.]]

 ...

 [[ 83. 133. 200.]
  [ 87. 137. 203.]
  [ 86. 134. 205.]
  ...
  [ 47.  82. 146.]
  [ 51.  86. 150.]
  [ 54.  89. 153.]]

 [[ 80. 130. 196.]
  [ 84. 134. 201.]
  [ 86. 134. 205.]
  ...
  [ 37.  69. 130.]
  [ 35.  68. 129.]
  [ 33.  66. 126.]]

 [[ 63. 116. 185.]
  [ 69. 122. 190.]
  [ 72. 124. 194.]
  ...
  [ 53.  90. 154.]
  [ 52.  89. 153.]
  [ 51.  88. 152.]]]
